---
title: "Simple metrics of biodiversity demonstrations"
output: 
    github_document:
        toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.dim = c(5,4))
library(dplyr)
library(ggplot2)
theme_set(theme_bw())
```

## Data

Get an SAD (here, using the New Hartford, CT BBS data; substitute here to use a different community)

```{r}

sad_long <- birdsize::new_hartford_clean %>%
  select(aou, speciestotal) %>%
  group_by(aou) %>%
  summarize(n = sum(speciestotal)) %>%
  ungroup() %>%
  left_join(birdsize::sd_table) %>%
  rename(spp = aou) %>%
  select(spp, genus, species, n)

sad_counts <- sad_long %>%
  #group_by(spp) %>%
  #tally() %>%
  arrange(desc(n)) %>%
  mutate(rank = dplyr::row_number()) %>%
  rename(abundance = n) %>%
  select(rank, abundance, genus, species) %>%
  group_by(abundance) %>%
  mutate(nspp = dplyr::n()) %>%
  ungroup() %>%
  mutate(prop_spp = nspp / max(rank))

head(sad_counts)

```

## Visualizing SADs

### Histogram

```{r}

sad_histogram <- ggplot(sad_counts, aes(abundance)) +
  geom_histogram() +
  xlab("Abundance") +
  ylab("Frequency") +
  ggtitle("Histogram")

sad_histogram


sad_histogram_bins2 <- ggplot(sad_counts, aes(abundance)) +
  geom_histogram(bins = 10) +
  xlab("Abundance") +
  ylab("Frequency") +
  ggtitle("Histogram")

sad_histogram_bins2
```


### PMF

```{r}

sad_pmfplot <- ggplot(sad_counts %>% select(abundance, prop_spp) %>% distinct(), aes(abundance, prop_spp)) +
  geom_col() +
  xlab("Abundance (N)") +
  ylab("Probability (P(N))") +
  ggtitle("Probability mass function (PMF)")

sad_pmfplot

```

### Rank-abundance plot

```{r}

sad_rankplot <- ggplot(sad_counts, aes(rank, abundance)) +
  geom_point() +
  geom_line() +
  xlab("Rank") +
  ylab("Abundance") +
  ggtitle("Rank-abundance plot") 

sad_rankplot



sad_rankplot_log <- ggplot(sad_counts, aes(rank, abundance)) +
  geom_point() +
  geom_line() +
  xlab("Rank") +
  ylab("Abundance") +
  ggtitle("Rank-abundance plot - log axis") +
  scale_y_log10()


sad_rankplot_log
```

### Cumulative distribution function

```{r}

sad_ecdf <- ecdf(sad_counts$abundance)

sad_counts <- sad_counts %>%
  mutate(cdf = sad_ecdf(abundance))

cdf_plot <- ggplot(sad_counts, aes(abundance, cdf)) + 
  geom_point() +
  geom_line() +
  xlab("Abundance") +
  ylab("Cumulative density") +
  ggtitle("Cumulative density function (CDF)") +
  ylim(0, 1)


sad_pmfplot

cdf_plot


sad_counts <- sad_counts %>%
  mutate(inverse_cdf = 1/cdf)


invcdf_plot <- ggplot(sad_counts, aes(inverse_cdf, abundance)) + 
  geom_point() +
  geom_line() +
  xlab("Inverse cumulative density") +
  ylab("Abundance") +
  ggtitle("Inverse cumulative density function (CDF)")

invcdf_plot
# 
# 
# ggplot(sad_counts, aes(inverse_cdf, abundance)) +
#   geom_point() +
#   geom_path()

```

## Fitted distributions

* Logseries (Fisher, METE, neutral)
* Lognormal 
* Power law
* Negative binomial

```{r}
library(sads)
logseries <- sads::fitls(sad_counts$abundance)
#plot(logseries)

sad_logseries_pred <- sad_counts %>%
  mutate(pred = radpred(logseries)$abund,
         fit = "Logseries")

ggplot(sad_logseries_pred, aes(rank, abundance)) + 
  geom_point() +
  geom_line(aes(y = pred)) +
  ggtitle("Logseries fit to empirical data")+
  xlab("Rank") +
  ylab("Abundance")  +
  scale_y_log10() 

```

```{r}


lognormal <- sads::fitlnorm(sad_counts$abundance)
#plot(lognormal)

sad_lognormal_pred <- sad_counts %>%
  mutate(pred = sads::radpred(lognormal)$abund,
         fit = "Lognormal")

ggplot(sad_lognormal_pred, aes(rank, abundance)) + 
  geom_point() +
  geom_line(aes(y = pred)) +
  ggtitle("Lognormal fit to empirical data") +
  xlab("Rank") +
  ylab("Abundance")  +
  scale_y_log10() 
```

```{r}



negbin <- sads::fitnbinom(sad_counts$abundance)
#plot(negbin)

sad_negbin_pred <- sad_counts %>%
  mutate(pred = sads::radpred(negbin)$abund,
         fit = 'Negative binomial')

ggplot(sad_negbin_pred, aes(rank, abundance)) + 
  geom_line(aes(y = pred)) +
    geom_point() +
  ggtitle("Negative binomial fit to empirical data") +
  xlab("Rank") +
  ylab("Abundance")  +
  scale_y_log10() 

```


```{r}

library(poweRlaw)

pwrlw <- displ$new(sad_counts$abundance)

mle_pars <- estimate_pars(pwrlw)

pwrlw$setPars(mle_pars$pars[1])

sad_pwrlw_pred <- sad_counts %>%
  mutate(pred = sort(dist_rand(pwrlw, n = 62), decreasing = T),
         fit = "Power law")

ggplot(sad_pwrlw_pred, aes(rank, abundance)) + 
  geom_line(aes(y = pred)) +
    geom_point() +
  ggtitle("Powerlaw fit to empirical data") +
  xlab("Rank") +
  ylab("Abundance") +
  scale_y_log10() 

```

```{r, fig.dim = c(6,4)}

all_pred <- bind_rows(sad_logseries_pred, sad_lognormal_pred, sad_negbin_pred, sad_pwrlw_pred) %>%
  rename(Fit = fit)

ggplot(all_pred, aes(rank, abundance)) +
  geom_point() + 
  geom_line(aes(y = pred, color = Fit), size = 1.2) +
  scale_y_log10() +
  ggtitle("All fits") +
  xlab("Rank") +
  ylab("Abundance") +
  scale_color_viridis_d(end = .8)


```


## Summary statistics

* Richness
* Evenness/diversity

****

* Hill numbers

```{r}

sad_counts_annual <- birdsize::new_hartford_raw %>%
  group_by(year, aou) %>%
  summarize(n = sum(speciestotal)) %>%
  arrange(desc(n)) %>%
  mutate(rank = dplyr::row_number()) %>%
  ungroup() %>%
  rename(spp = aou) %>%
  filter(year <= 2018)


sad_counts_annual_wide <- sad_counts_annual %>%
  select(year, spp, n) %>%
  tidyr::pivot_wider(id_cols = year, names_from = spp, values_from = n, values_fill = 0)

library(hillR)
library(vegan)

sads_counts_noyear <- select(sad_counts_annual_wide, -year)

sad_counts_otherdis <- sad_counts_annual %>%
  group_by(year) %>%
  summarize(richness = length(unique(spp)),
         shannon = vegan::diversity(n),
         invsimpson = vegan::diversity(n, index = "invsimpson")) %>%
  ungroup()

sad_dis <-sad_counts_annual_wide %>%
  select(year) %>%
  mutate(hill_0 = hill_taxa(sads_counts_noyear, q = 0),
         hill_1 = hill_taxa(sads_counts_noyear, q = 1),
         hill_2 = hill_taxa(sads_counts_noyear, q = 2)) %>%
  left_join(sad_counts_otherdis) %>%
  mutate(exp_shannon = exp(shannon))

```

```{r, fig.dim = c(9,9)}

ggplot(sad_counts_annual, aes(rank, n)) + 
  geom_line() +
  geom_point() +
  facet_wrap(vars(year)) +
  xlab("Rank") +
  ylab("Abundance") +
  ggtitle("A timeseries of SADs")

```


```{r}

h0 = ggplot(sad_dis, aes(year, hill_0)) +
  geom_point() +
  geom_line() +
  ggtitle("Species richness (q = 0)") +
  xlab("Year") +
  ylab("Hill number (q = 0)")

```


```{r}

h1= ggplot(sad_dis, aes(year, hill_1)) +
  geom_point() +
  geom_line() +
  ggtitle("exp(Shannon index) (q = 1)") +
  xlab("Year") +
  ylab("Hill number (q = 1)")

```


```{r}

h2 = ggplot(sad_dis, aes(year, hill_2)) +
  geom_point() +
  geom_line() +
  ggtitle("Inverse Simpson (q = 2)") +
  xlab("Year") +
  ylab("Hill number (q = 2)")

```

```{r, fig.dim = c(4,6)}
library(multipanelfigure)

multi_panel_figure(columns = 1, rows = 3) %>%
  fill_panel(h0) %>%
  fill_panel(h1) %>%
  fill_panel(h2)

```

```{r}

rats <- portalr::abundance()

rat_species <- portalr::load_rodent_data()$species_table %>% select(species, scientificname, commonname)

ratcounts <- rats %>%
  filter(period > 450) %>%
  tidyr::pivot_longer(-period, names_to = "species", values_to = "abundance") %>%
  group_by(species) %>%
  summarize(Abundance = sum(abundance)) %>%
  left_join(rat_species) %>%
  select(-species) %>%
  arrange(desc(Abundance)) %>%
  rename(`Scientific name` = scientificname,
         `Common name` = commonname)

head(ratcounts)

ratranks <- ratcounts %>%
  mutate(rank = dplyr::row_number())

```
